[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>"
]
description = "Setup Garden CLI in your CI/CD Pipeline"
license = "MIT"
name = "garden"
version = "0.1.0"
keywords = [
  "garden"
]